---
title: "2025-04-17"
author: "John Hinkle"
format: html
editor: visual
self-contained: true
---

## Load data

```{r}
library(tidyverse)
library(ggplot2)
d <- read_csv("https://raw.githubusercontent.com/difiore/ada-datasets/refs/heads/main/chimpgrooming.csv", col_names = TRUE)
head(d)
```

## x

```{r}
library(ggplot2)
library(cowplot)

p1 <- ggplot(d, aes(x = subject, y = duration)) +
  geom_boxplot() +
  theme_classic() +
  theme(axis.text.x = element_text(angle = 45, vjust = 0.5, hjust=0.5))

p2 <- ggplot(d, aes(x = reprocondition, y = duration)) +
  geom_boxplot() +
  theme_classic() +
  labs(y=NULL)

p3 <- ggplot(d, aes(x = parity, y = duration)) +
  geom_boxplot() +
  theme_classic() +
  labs(y=NULL)

plot_grid(p1, p2, p3, nrow=1)
```

## Random intercept model

```{r}
library(lme4)
m <- lmer(data = d,
          duration ~ reprocondition + parity + (1|subject))
summary(m)
```

## Models

```{r}
library(lmtest)
fuller <- lmer(data = d,
          duration ~ reprocondition + parity + (1|subject))
reduced <- lmer(data = d,
          duration ~ parity + (1|subject), REML = FALSE)

anova(fuller, reduced, test = "Chisq")
```

## Random slopes models

```{r}
full <- lmer(data = d,
          duration ~ reprocondition + parity + 
            (1 + reprocondition|subject) + 
            (1 + parity|subject), REML = FALSE)
summary(full)
```

## Model

```{r}
minusRC <- lmer(data = d,
          duration ~ parity + 
            (1 + reprocondition|subject) + 
            (1 + parity|subject), REML = FALSE)
summary(minusRC)
```

## Model

```{r}
minusP <- lmer(data = d,
          duration ~ reprocondition + 
            (1 + reprocondition|subject) + 
            (1 + parity|subject), REML = FALSE)
summary(minusP)
```

```{r}
anova(minusRC, full, test = "Chisq") # adding RC adds explanatory power
anova(minusP, full, test = "Chisq") # adding P adds explanatory power
```

```{r}
null <- lmer(data = d, duration ~
               (1 + reprocondition|subject) + 
               (1 + parity|subject), REML =  FALSE)

#library(AICcmodavg)

```

# Otters

```{r}
o <- read_csv("https://raw.githubusercontent.com/difiore/ada-datasets/refs/heads/main/Bowden-ParryOtter.csv", col_names = TRUE)
head(o)
```
