---
title: "2025-02-04"
author: "John Hinkle"
format: html
editor: visual
---

## February 4th, 2025 Class Notes

load

```{r}
library(tidyverse)
library(ggplot2)

f <- "https://raw.githubusercontent.com/difiore/ada-datasets/refs/heads/main/KamilarAndCooperData.csv"
d <- read_csv(f, col_names = TRUE)
```

### Scatter plot with lines

```{r}
p <- ggplot(data = d, aes(
  x = log(Body_mass_female_mean), 
  y = log(Brain_Size_Female_Mean)
)) +
  geom_point(na.rm = TRUE, color = '#bf5700') +
  geom_smooth(method ="lm", na.rm = TRUE, color ='black') + # trend line with confidence interval
  geom_vline(xintercept = 7, linetype='dotted', color='green4') + # vertical line at x = 7 
  geom_hline(yintercept = 3, linetype='dotdash', color='skyblue') # horizonal line at y = 3
```

{cowplot} package

```{r}
library(cowplot)
# arrange plots into a multi-paneled figure
plot_grid(p, p, p, p)
```

### Filtering with {dplyr}

```{r}
s <- filter(d, Family == "Hominidae" & Mass_Dimorphism > 2)
```

### Selecting with {dplyr}

```{r}
s <- select(d, Family, Genus, Body_mass_male_mean)
```

### Sorting with {dplyr}

```{r}
s <- arrange(d, Family, Genus, desc(Body_mass_male_mean))
```

### In-Class Exercise

```{r}
file <- "https://raw.githubusercontent.com/difiore/ada-datasets/refs/heads/main/IMDB-movies.csv"
df <- read_csv(file, col_names = TRUE)
```

Create 'comedy' variable

```{r}
df <- df |> mutate(Comedy = if_else(grepl("Comedy", genres, ignore.case = TRUE), TRUE, FALSE))
```

Count total movies and all comedy movies

```{r}
df |> summarise(n(), sum(Comedy))
```

Ranking

```{r}
df <- df |> mutate(ranking = case_when(
  0 < averageRating & averageRating < 3.3 ~ "low",
  3.3 <= averageRating & averageRating < 6.7 ~ "mid",
  6.7 <= averageRating & averageRating < 10 ~ "high"
))
```

```{r}
df |> group_by(genres) |> summarise(n(), mean(runtimeMinutes, na.rm=TRUE))
```

Printing a numerical vector

```{r}
for (i in 1:5) {
  print(i**2)
}
```

Printing a text vector

```{r}
sequences <- c("AGATGCTACATACGGCAGCTGACGTCTCGCGCGATAGCGTAGCTATAGCT", "CGATAGCGTAGCTATACCGCGCGCGCGATATAGAGCTCTGT", "ATTTCATGACGATCATGACTAGCTA", "GGATCATAGCTACGTAGCTGC", "GCTAGCACGTGATTATAACTCATACGAGCTGATATACGT")

for (i in sequences) {
  print(i)
}
```

text

```{r}
cumRT <- 0

for (i in df$runtimeMinutes){
  if (!is.na(i)){
    cumRT <- cumRT + i
  }
  print(cumRT)
}
```

Join tables

```{r}
f1 <- "https://raw.githubusercontent.com/difiore/ada-datasets/refs/heads/main/papers.csv"
f2 <- "https://raw.githubusercontent.com/difiore/ada-datasets/refs/heads/main/creators.csv"

p <- read_csv(f1, col_names = TRUE)
c <- read_csv(f2, col_names = TRUE)
```

```{r}
p <- p |> 
  separate_wider_delim(cols = Author,
                       delim = ";",
                       names = c("First Author", "A2", "A3", "A4"),
                       too_few = "align_start", 
                       too_many = "drop") |>
  mutate(A2 = str_trim(A2, "both"),
         A3 = str_trim(A3, "both"),
         A4 = str_trim(A4, "both"))

c <- c |> distinct()
```
