---
title: "2024-04-03"
author: "John Hinkle"
format: html
editor: visual
self-contained: true
---

## Multiple regression and ANCOVA

```{r}
library(tidyverse)
library(car)
library(jtools)
```

```{r}
z <- read_csv("https://raw.githubusercontent.com/difiore/ada-datasets/refs/heads/main/zombies.csv", col_names = TRUE)
```

```{r}
m <- lm(height ~ weight + age + gender, data = z)
summary(m)
```

```{r}
coef(m)[["weight"]]
```

```{r}
WEIGHT <- 132 # in pounds
AGE <- 29 # in years
GENDER <- 1 # male = 1, female = 0

(HEIGHT <- coef(m)[["(Intercept)"]] + coef(m)[["weight"]]*(WEIGHT) + coef(m)[["age"]]*(AGE) + coef(m)[["genderMale"]]*(GENDER)) # in inches

(ci <- predict(m,
              newdata = data.frame(age = AGE, weight = WEIGHT, gender = "Male"),
              interval = "prediction",
              level = 0.95)) # height confidence interval
```

```{r}
m1 <- lm(height ~ age, data = z)
effect_plot(m1,
            pred = age,
            interval = TRUE,
            int.type = "confidence",
            int.width = 0.95,
            plot.points = TRUE
            )

m2 <- lm(height ~ age + weight, data = z)
effect_plot(m2,
            pred = age,
            interval = TRUE,
            int.type = "confidence",
            int.width = 0.95,
            plot.points = TRUE
            )

m3 <- lm(height ~ age + weight + gender, data = z)
effect_plot(m3,
            pred = age,
            interval = TRUE,
            int.type = "confidence",
            int.width = 0.95,
            plot.points = TRUE
            )
```

```{r}

```

Next

```{r}
a <- read_csv("https://raw.githubusercontent.com/difiore/ada-datasets/refs/heads/main/AVONETdataset1.csv")

accs <- a |> 
  filter(Order1 == "Accipitriformes") |>
  mutate(logMass = log(Mass)) |>
  mutate(logRS = log(Range.Size))
```

```{r}
# 1 if primary lifestyle applies, 0 if it does not
# logRS = 13.2715 + 0.2650(logMass) - 0.3356(generalist) - 1.3121(insessorial) - 0.3268(terrestrial)
m1 <- lm(logRS ~ logMass + Primary.Lifestyle, data = accs)
summary(m1)
```

Width of a prediction interval is always wider than the confidence interval

```{r}
library(tidyverse)
d <- read_csv("https://raw.githubusercontent.com/difiore/ada-datasets/refs/heads/main/AVONETdataset1.csv")
# winnow dataset to the specified variables
d <- d |> select(Species1, Family1, Order1, Beak.Length_Culmen, Beak.Width, Beak.Depth, Tarsus.Length, Wing.Length, Tail.Length, Mass, Habitat, Migration, Trophic.Level, Trophic.Niche, Min.Latitude, Max.Latitude, Centroid.Latitude, Primary.Lifestyle, Range.Size)

d <- d |> mutate(
  logMass = log(Mass),
  logRS = log(Range.Size),
  logBeak = log(Beak.Length_Culmen),
  logTarsus = log(Tarsus.Length),
  Migration = as.factor(Migration)
)
relBeak <- lm(logMass ~ logBeak, data = d)
relTarsus <- lm(logMass ~ logTarsus, data = d)
d <- d |>
  mutate(relBeak = relBeak$residuals,
         relTarsus = relTarsus$residuals)
```

```{r}
m1 <- lm(logBeak ~ logRS * Migration, data = d) # most complex (full) model
m2 <- lm(logBeak ~ logRS + Migration, data = d) 
m3 <- lm(logBeak ~ logRS, data = d)
m4 <- lm(logBeak ~ Migration, data = d)
m5 <- lm(logBeak ~ 1, data = d) # intercept only
```

```{r}
anova(m2, m1, test = "F")
```

```{r}

```

```{r}

```

```{r}

```
